### ISSUE TITLE
Não funciona

### ISSUE THREAD

**Issue by BenevidesLecontes** [vtex-apps/dreamstore#63]
Olá, estou tentando correr esse projeto e nunca funciona, clono o projeto, corro com vtex link e tento acessar as rotas que mostra no console e não mostra nada. Tento usar a rota default e tomo o erro na imagem:
PS: A unica branch que funciona é a `account/pages`
![render server error](https://user-images.githubusercontent.com/1839361/43828880-0e1eff02-9ad4-11e8-9054-acb3f200513e.png)

**Comment by GustavoACupula** [comment]
Isso acontece porque você tá usando uma versão diferente do app publicado pela VTEX, o store-components. Tente fixar a versão dele pra 1.11.0 por enquanto, quando houver outra atualização da VTEX desse app é só colocar o "x" na versão de novo que provavelmente já terá normalizado.

**Comment by BenevidesLecontes** [comment]
@GustavoACupula dá no mesmo com a sua sugestão, inclusive na app que estou desenvolvendo tudo parou de funcionar, o page editor já não aparece, que até ontem aparecia, o buybutton também dá erro ao clicar. Tá inviável desenvolver.
<img width="670" alt="screen shot 2018-08-08 at 22 39 11" src="https://user-images.githubusercontent.com/1839361/43873191-e8ae443e-9b5b-11e8-9c88-07ace06a9f80.png">

**Comment by brunojdo** [comment]
Boa tarde @BenevidesLecontes voce pode mandar o workspace com o problema? 

Por favor, 
1. Crie um workspace novo
2. Execute `vtex install vtex.dreamstore` 
3. Acesse workspace no browser e veja se o problema persiste. 

Caso o problema persista posta aqui o problema e o workspace.
